# NumPy入門

### リソース
- [8 - NumPyの手引き](https://nuinfo-seminar.esa.io/posts/38)

In [2]:
import numpy as np

In [4]:
arr1 = np.array(
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ]
)

arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
arr2 = np.ndarray(
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ]
)

arr2

TypeError: 'list' object cannot be interpreted as an integer

$\to$ `ndarray`は関数ではなく型、`np.array`は`ndarray`を生成する関数

### テンソルのスライスは可能？

In [13]:
tensor = np.array(
    [
        [
            [0, 1, 2],
            [3, 4, 5]
        ],
        [
            [1, 2, 3],
            [4, 5, 6]
        ]
    ]
)

In [8]:
tensor

array([[[0, 1, 2],
        [3, 4, 5]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [15]:
tensor[:, 1, :]

array([[3, 4, 5],
       [4, 5, 6]])

In [16]:
tensor[:, 1:2, :]

array([[[3, 4, 5]],

       [[4, 5, 6]]])

## 整数配列による要素の選択

In [18]:
arr = np.array(
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ]
)

arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
arr[[0, 2, 1], [1, 1, 0]]

array([2, 8, 4])

## 演算のブロードキャスト

In [24]:
A = np.array(
    [
        [0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]
    ]
)

B = np.array([1, 2, 3])

display(A)
display(B)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

array([1, 2, 3])

In [25]:
A + B

array([[ 1,  3,  5],
       [ 4,  6,  8],
       [ 7,  9, 11]])

In [28]:
a =np.array( [[[6, 2, 0]], 
              [[1, 9, 7]]])

b = np.array([[6],
              [2],
              [8]])

display(a)
display(b)

array([[[6, 2, 0]],

       [[1, 9, 7]]])

array([[6],
       [2],
       [8]])

In [27]:
a + b

array([[[12,  8,  6],
        [ 8,  4,  2],
        [14, 10,  8]],

       [[ 7, 15, 13],
        [ 3, 11,  9],
        [ 9, 17, 15]]])

In [29]:
print(a.shape)
print(b.shape)

(2, 1, 3)
(3, 1)


### ブロードキャストの仕組み

```
a.shape -> (2, 1, 3)
b.shape -> (3, 1)
```

$\downarrow$ 次元を揃える

```
(2, 1, 3)
 ↓
(2  3, 1)
```

$\downarrow$ 1である次元をコピーして埋める

```
(2, 3, 3)
    ↑  ↓
(2, 3, 3)
```

$\downarrow$ 最終的なshape

```
(2, 3, 3)
```

In [31]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
])

In [32]:
arr.mean(axis=0)

array([2.5, 3.5, 4.5])

In [33]:
arr.mean(axis=1)

array([2., 5.])

In [34]:
tensor = np.array(
    [
        [
            [0, 1, 2],
            [3, 4, 5]
        ],
        [
            [1, 2, 3],
            [4, 5, 6]
        ]
    ]
)

In [35]:
tensor.shape

(2, 2, 3)

In [36]:
tensor.mean(axis=0)

array([[0.5, 1.5, 2.5],
       [3.5, 4.5, 5.5]])

In [37]:
tensor.mean(axis=1)

array([[1.5, 2.5, 3.5],
       [2.5, 3.5, 4.5]])

In [38]:
tensor.mean(axis=2)

array([[1., 4.],
       [2., 5.]])